databases:
  - name: rails-crud-redux
    databaseName: rails-crud-redux
    user: rails_crud_redux_user

services:
  - type: web
    name: React-Redux_rails7
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-crud-redux
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

        
#  databases:
#   - name: rails-crud-redux
#     databaseName: rails-crud-redux
#     user: rails-crud-redux
#     plan: free

# services:
#   - type: web
#     name: mysitered
#     runtime: ruby
#     plan: free
#     buildCommand: "./bin/render-build.sh"
#     # Uncomment for paid instances
#     # preDeployCommand: "bundle exec rails db:migrate"
#     startCommand: "bundle exec rails server"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: mysite
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false
#       - key: WEB_CONCURRENCY
#         value: 2



       